# Generated by Django 4.0.5 on 2022-06-10 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inscritos',
            options={'ordering': ['nome', 'edicao'], 'verbose_name': 'Participante', 'verbose_name_plural': 'Participantes'},
        ),
    ]
