# Generated by Django 3.2.12 on 2022-06-21 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0005_alter_cospobre_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cospobre',
            name='imagem',
            field=models.ImageField(null=True, upload_to='cospobre/images', verbose_name='Imagem'),
        ),
    ]
