# Generated by Django 3.2.12 on 2022-06-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0006_alter_cospobre_imagem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cospobre',
            options={'ordering': ['nome', 'personagem', 'edicao'], 'verbose_name': 'Cospobre', 'verbose_name_plural': 'Cospobres'},
        ),
        migrations.AddField(
            model_name='cospobre',
            name='personagem',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
