# Generated by Django 3.2.12 on 2022-06-29 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0007_auto_20220621_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artistas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=150)),
                ('experiencia', models.IntegerField()),
                ('obrasPublicadas', models.IntegerField()),
                ('obrasFuturas', models.TextField(max_length=400)),
                ('instagram', models.CharField(blank=True, max_length=200)),
                ('facebook', models.CharField(blank=True, max_length=200)),
                ('devianart', models.CharField(blank=True, max_length=200)),
                ('blog', models.CharField(blank=True, max_length=200)),
                ('outraRedeSocial', models.CharField(blank=True, max_length=200)),
                ('arquivos', models.FileField(blank=True, null=True, upload_to='artistas/files', verbose_name='Arquivos')),
                ('edicao', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='inscricao.edicao')),
            ],
            options={
                'verbose_name': 'Artista',
                'verbose_name_plural': 'Artistas',
                'ordering': ['nome', 'edicao'],
            },
        ),
    ]
