# Generated by Django 3.2.12 on 2022-08-09 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0009_alter_edicao_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cospobre',
            name='direitoImagem',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='cospobre',
            name='som',
            field=models.FileField(null=True, upload_to='cospobre/sounds', verbose_name='Musica'),
        ),
        migrations.CreateModel(
            name='Cosplay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=150)),
                ('personagem', models.CharField(max_length=150, null=True)),
                ('imagem', models.ImageField(null=True, upload_to='cosplay/images', verbose_name='Imagem')),
                ('som', models.FileField(null=True, upload_to='cosplay/sounds', verbose_name='Musica')),
                ('direitoImagem', models.BooleanField(default=False, null=True)),
                ('nota_1', models.IntegerField(default=0, null=True)),
                ('nota_2', models.IntegerField(default=0, null=True)),
                ('nota_3', models.IntegerField(default=0, null=True)),
                ('edicao', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='inscricao.edicao')),
            ],
            options={
                'verbose_name': 'Cosplay',
                'verbose_name_plural': 'Cospobres',
                'ordering': ['nome', 'personagem', 'edicao'],
            },
        ),
    ]
