# Generated by Django 3.2.12 on 2022-08-10 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0010_auto_20220809_0314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fliq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
            ],
            options={
                'verbose_name': 'FLiQ',
                'verbose_name_plural': 'FLiQ',
                'ordering': ['numero'],
            },
        ),
        migrations.AlterModelOptions(
            name='cosplay',
            options={'ordering': ['nome', 'personagem', 'edicao'], 'verbose_name': 'Cosplay', 'verbose_name_plural': 'Cosplays'},
        ),
    ]
