# Generated by Django 3.2.12 on 2022-08-10 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0012_auto_20220810_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistas',
            name='total',
            field=models.FloatField(default=0, null=True),
        ),
    ]
