# Generated by Django 3.2.12 on 2022-08-10 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0013_artistas_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistas',
            name='fliq',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
