# Generated by Django 3.2.12 on 2023-07-15 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0017_auto_20230714_1322'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notascosplay',
            options={'ordering': ['edicao', 'total_nota', 'nome', 'personagem'], 'verbose_name': 'Nota Cosplay', 'verbose_name_plural': 'Notas Cosplays'},
        ),
        migrations.AlterModelOptions(
            name='notascospobre',
            options={'ordering': ['edicao', 'total_nota', 'nome', 'personagem'], 'verbose_name': 'Nota Cospobre', 'verbose_name_plural': 'Notas Cospobres'},
        ),
    ]
